name: Build and Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@octopusdeploy'

      - name: npm build and package
        run: |
          npm ci
          npm run build
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.INTEGRATIONS_NPM_ACCESS_TOKEN }}